Group
IF-128-Java/course_evaluation pull request #116
Opened 2021-09-21 22:35 UTC by team-part

2021-09-22 05:55 UTC, yapollo2002 approved these changes

2021-09-22 07:43 UTC, Forfend requested changes

2021-09-22 07:43 UTC, Forfend commented on src/main/java/ita/softserve/course_evaluation/dto/TeacherStatDto.java
> +    }
get and set methods are obsolete here, since you are using ```@Data```

2021-09-22 08:35 UTC, yapollo2002 approved these changes

2021-09-23 08:17 UTC, James-Koval approved these changes

2021-09-23 17:53 UTC, Arsen-Kushnir approved these changes

2021-09-23 17:56 UTC, merged