Fixed bugs with Post and Put requests.
IF-128-Java/course_evaluation pull request #29
Opened 2021-08-03 20:00 UTC by James-Koval

2021-08-04 05:03 UTC, VovaProtsiv requested changes

2021-08-04 05:03 UTC, VovaProtsiv commented on src/test/java/ita/softserve/course_evaluation/repository/CourseRepositoryTests.java
>      }
Why are you comment tests? Please, fix findByCourseName method in CourseRepository.

2021-08-04 20:17 UTC, VovaProtsiv approved these changes

2021-08-05 07:10 UTC, Arsen-Kushnir approved these changes

2021-08-05 07:14 UTC, merged