Made findByName endpoint
IF-128-Java/course_evaluation pull request #49
Opened 2021-08-14 19:35 UTC by James-Koval

Made findByName endpoint (method and query), refactored and reformatted code connected with this logic, changed tests

2021-08-14 20:05 UTC, VovaProtsiv requested changes

2021-08-14 20:05 UTC, VovaProtsiv commented on src/main/java/ita/softserve/course_evaluation/controller/CourseController.java
>      }
Just return dto list. Don't return not found

2021-08-14 20:05 UTC, VovaProtsiv commented on src/main/java/ita/softserve/course_evaluation/controller/CourseController.java
> +    }
Just return dto list. Don't return not found

2021-08-14 20:05 UTC, VovaProtsiv commented on src/main/java/ita/softserve/course_evaluation/entity/Course.java
>      @Column(name = "course_Name", nullable = false)
remove commented code

2021-08-14 20:05 UTC, VovaProtsiv commented on src/main/java/ita/softserve/course_evaluation/repository/CourseRepository.java
JpaRepository extends CrudRepository

2021-08-15 13:25 UTC, Arsen-Kushnir approved these changes

2021-08-15 13:40 UTC, VovaProtsiv approved these changes

2021-08-15 13:42 UTC, merged