Question entity
IF-128-Java/course_evaluation pull request #7
Opened 2021-07-21 10:21 UTC by FedenkoM

2021-07-22 11:03 UTC, Forfend requested changes

2021-07-22 11:03 UTC, Forfend commented on src/main/java/ita/softserve/course_evaluation/service/AnswerToFeedbackService.java
> +    void deleteAnswerById(long id);
please, add blank line here

2021-07-22 11:03 UTC, Forfend commented on src/main/java/ita/softserve/course_evaluation/service/QuestionService.java
> +    void deleteQuestionById(long id);
please, add blank line here

2021-07-22 11:03 UTC, Forfend commented on src/main/java/ita/softserve/course_evaluation/service/impl/AnswerToFeedbackServiceImpl.java
> +                        .orElseThrow(() -> new RuntimeException("Answer was not found for id: " + id)));
It's better to create a specific exception, like AnswerNotFoundException, but I believe if there is no answer in DB - we get ```null```

2021-07-24 09:08 UTC, Forfend requested changes

2021-07-24 09:08 UTC, Forfend commented on src/main/java/ita/softserve/course_evaluation/entity/Feedback.java
> +public class Feedback {
```@Table```

2021-07-24 09:52 UTC, FedenkoM commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/io.springfox/springfox-swagger-ui -->
done

2021-07-24 09:53 UTC, FedenkoM commented on src/main/java/ita/softserve/course_evaluation/controller/AnswerToFeedbackController.java
> +    @PostMapping("/addAnswer")
edite annotation

2021-07-24 09:53 UTC, FedenkoM commented on src/main/java/ita/softserve/course_evaluation/controller/QuestionController.java
> +    @GetMapping("")
Remove "" from get method

2021-07-24 09:53 UTC, FedenkoM commented on src/main/java/ita/softserve/course_evaluation/controller/QuestionController.java
> +    @PostMapping("/addQuestion")
edited

2021-07-24 09:54 UTC, FedenkoM commented on src/main/java/ita/softserve/course_evaluation/controller/QuestionController.java
> +            ,@RequestBody QuestionDto question){
done

2021-07-24 09:54 UTC, FedenkoM commented on src/main/java/ita/softserve/course_evaluation/service/AnswerToFeedbackService.java
> +    void deleteAnswerById(long id);
added blank line

2021-07-24 10:28 UTC, FedenkoM commented on src/main/java/ita/softserve/course_evaluation/entity/Feedback.java
> +public class Feedback {
done

2021-07-24 10:29 UTC, FedenkoM commented on src/main/java/ita/softserve/course_evaluation/service/QuestionService.java
> +    void deleteQuestionById(long id);
done

2021-07-24 10:30 UTC, FedenkoM commented on src/main/java/ita/softserve/course_evaluation/controller/QuestionController.java
> +//                ? new ResponseEntity<>(question, HttpStatus.OK)
removed

2021-07-26 07:05 UTC, Forfend approved these changes

2021-07-26 07:07 UTC, merged