Add Notification about new FeedbackRequest
IF-128-Java/course_evaluation pull request #80
Opened 2021-09-01 10:42 UTC by Farleo

add status to feedback request
delete duration column
daily check available student and feedback request

2021-09-02 17:44 UTC, Arsen-Kushnir approved these changes

2021-09-03 13:46 UTC, VovaProtsiv requested changes

2021-09-03 13:46 UTC, VovaProtsiv commented on src/main/java/ita/softserve/course_evaluation/dto/UserDtoMapper.java
>  	}
if null return empty list

2021-09-03 13:46 UTC, VovaProtsiv commented on src/main/java/ita/softserve/course_evaluation/repository/FeedbackRequestRepository.java
use one style for sql commands   (SELECT  From where)

2021-09-03 13:46 UTC, VovaProtsiv commented on src/main/java/ita/softserve/course_evaluation/repository/UserRepository.java
>  }
use one style for sql commands (SELECT on and)

2021-09-03 13:46 UTC, VovaProtsiv commented on src/main/java/ita/softserve/course_evaluation/service/impl/NotificationServiceImpl.java
> +		}
use log

2021-09-03 13:46 UTC, VovaProtsiv commented on src/test/java/ita/softserve/course_evaluation/repository/QuestionRepositoryTest.java
>          System.out.println(feedbackRequest);
remove System.out.println

2021-09-03 20:42 UTC, VovaProtsiv approved these changes

2021-09-04 05:16 UTC, merged